config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registration" }
  resources :users
  

  # NESTED RESOURCES FOR COMMENTS
  resources :products do
    resources :comments 
  end
  

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  get '/products/:id', to: 'products#show'

  post '/static_pages/thank_you'

  root 'static_pages#index'

  # root 'static_pages#landing_page'

  # root 'products#index'

  # root 'orders#index'

  post 'payments/create'

  resources :orders, only: [:index, :show, :create, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
end

app/views/layouts/_alert.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-danger alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_notice.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-success alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Berlin Bike</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
  </head>
  <body>
   
    <%#--- NAVIGATION BAR ---%>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid headerBar">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home", static_pages_index_url%>  </li>
            <li><%= link_to "Product", products_url%>  </li>
            <li><%= link_to "Order", orders_url%></li>
            <li><%= link_to "About", static_pages_about_url%></li>
            <li><%= link_to "Contact", static_pages_contact_url%></li>
            
            <%#SIGNOUT, LOGIN & SIGN UP%>
            <li>
              <% if user_signed_in?%>
                <% if current_user.admin?%>
                <%= link_to('Accounts', users_url) %>
                <%end%>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete)%> </li>
                <% else%>
                <%= link_to('Login', new_user_session_path)%>
              <% end %>
            </li>
          </ul>
          
          <%# SEARCH BAR %>
          <%= form_tag("/products", method: "get", class:"navbar-form nav-left search_form", role:"search") do %>
            <%= label_tag(:q, "") %>
            <%= text_field_tag(:q,nil, class: "", placeholder: "Search...") %>
            <%= submit_tag("Search") %>
          <% end %>
        </div>
      
      </div>
    </nav>


  <%#NOTICE & ALERTS%>
  <% if notice %>
    <%= render 'layouts/notice' %>
  <% end %>
  <% if alert %>
    <%= render 'layouts/alert' %>
  <% end %>
    
  <!-- Wrapper to setup footer at the bottom -->
  <div class="wrapper">
    <%= yield %>
  </div>
  
  <%#--- FOOTER ---%>
  <footer class="site_footer">
    &copy; 2017 Bike Berlin | <span class="rey_kuizon">Design by: Rey Kuizon </span>
   
  </footer>

  <!-- Bootstrap core JS -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
   
  </body>
</html>